const languages = [
    {
      no: "0",
      name: "Auto",
      native: "Detect",
      code: "auto",
    },
    {
        no: "1",
        name: "Assamese",
        native: "অসমীয়া",
        code: "as",
      },
      {
        no: "2",
        name: "Bengali",
        native: "বাংলা",
        code: "bn",
      },
      {
        no: "3",
        name: "Nepali",
        native: "नेपाल",
        code: "ne",
      },
      {
        no: "4",
        name: "Marathi",
        native: "मराठी",
        code: "mr",
      },
      {
        no: "5",
        name: "Punjabi",
        native: "ਪੰਜਾਬੀ",
        code: "pa",
      },
      {
        no: "6",
        name: "Tamil",
        native: "தமிழ்",
        code: "ta",
      },
      {
        no: "7",
        name: "Telugu",
        native: "తెలుగు",
        code: "te",
      },{
        no: "8",
        name: "Sanskrit",
        native: "संस्कृत-",
        code: "sa",
      },
      
    {
      no: "9",
      name: "Afrikaans",
      native: "Afrikaans",
      code: "af",
    },
    {
      no: "10",
      name: "Albanian",
      native: "Shqip",
      code: "sq",
    },
    {
      no: "11",
      name: "Arabic",
      native: "عربي",
      code: "ar",
    },
    {
      no: "12",
      name: "Armenian",
      native: "Հայերէն",
      code: "hy",
    },
    
    {
      no: "13",
      name: "Azerbaijani",
      native: "آذربایجان دیلی",
      code: "az",
    },
    {
      no: "14",
      name: "Basque",
      native: "Euskara",
      code: "eu",
    },
    {
      no: "15",
      name: "Belarusian",
      native: "Беларуская",
      code: "be",
    },
    {
      no: "16",
      name: "Bulgarian",
      native: "Български",
      code: "bg",
    },
    {
      no: "17",
      name: "Catalan",
      native: "Català",
      code: "ca",
    },
    {
      no: "18",
      name: "Chinese (Simplified)",
      native: "中文简体",
      code: "zh-CN",
    },
    {
      no: "19",
      name: "Chinese (Traditional)",
      native: "中文繁體",
      code: "zh-TW",
    },
    {
      no: "20",
      name: "Croatian",
      native: "Hrvatski",
      code: "hr",
    },
    {
      no: "21",
      name: "Czech",
      native: "Čeština",
      code: "cs",
    },
    {
      no: "22",
      name: "Danish",
      native: "Dansk",
      code: "da",
    },
    {
      no: "23",
      name: "Dutch",
      native: "Nederlands",
      code: "nl",
    },
    {
      no: "24",
      name: "English",
      native: "English",
      code: "en",
    },
    {
      no: "25",
      name: "Estonian",
      native: "Eesti keel",
      code: "et",
    },
    {
      no: "26",
      name: "Filipino",
      native: "Filipino",
      code: "tl",
    },
    {
      no: "27",
      name: "Finnish",
      native: "Suomi",
      code: "fi",
    },
    {
      no: "28",
      name: "French",
      native: "Français",
      code: "fr",
    },
    {
      no: "29",
      name: "Galician",
      native: "Galego",
      code: "gl",
    },
    {
      no: "30",
      name: "Georgian",
      native: "ქართული",
      code: "ka",
    },
    {
      no: "31",
      name: "German",
      native: "Deutsch",
      code: "de",
    },
    {
      no: "32",
      name: "Greek",
      native: "Ελληνικά",
      code: "el",
    },
    {
      no: "33",
      name: "Haitian Creole",
      native: "Kreyòl ayisyen",
      code: "ht",
    },
    {
      no: "34",
      name: "Hebrew",
      native: "עברית",
      code: "iw",
    },
    {
      no: "35",
      name: "Hindi",
      native: "हिन्दी",
      code: "hi",
    },
    {
      no: "36",
      name: "Hungarian",
      native: "Magyar",
      code: "hu",
    },
    {
      no: "37",
      name: "Icelandic",
      native: "Íslenska",
      code: "is",
    },
    {
      no: "38",
      name: "Indonesian",
      native: "Bahasa Indonesia",
      code: "id",
    },
    {
      no: "39",
      name: "Irish",
      native: "Gaeilge",
      code: "ga",
    },
    {
      no: "40",
      name: "Italian",
      native: "Italiano",
      code: "it",
    },
    {
      no: "41",
      name: "Japanese",
      native: "日本語",
      code: "ja",
    },
    {
      no: "42",
      name: "Korean",
      native: "한국어",
      code: "ko",
    },
    
    {
      no: "43",
      name: "Portuguese",
      native: "Português",
      code: "pt",
    },
    {
      no: "44",
      name: "Romanian",
      native: "Română",
      code: "ro",
    },
    {
      no: "45",
      name: "Russian",
      native: "Русский",
      code: "ru",
    },
    {
      no: "46",
      name: "Serbian",
      native: "Српски",
      code: "sr",
    },
    {
      no: "47",
      name: "Slovak",
      native: "Slovenčina",
      code: "sk",
    },
    {
      no: "48",
      name: "Slovenian",
      native: "Slovensko",
      code: "sl",
    },
    {
      no: "49",
      name: "Spanish",
      native: "Español",
      code: "es",
    },
    {
      no: "50",
      name: "Swahili",
      native: "Kiswahili",
      code: "sw",
    },
    {
      no: "51",
      name: "Swedish",
      native: "Svenska",
      code: "sv",
    },
    {
      no: "52",
      name: "Thai",
      native: "ไทย",
      code: "th",
    },
    {
      no: "53",
      name: "Turkish",
      native: "Türkçe",
      code: "tr",
    },
    {
      no: "54",
      name: "Ukrainian",
      native: "Українська",
      code: "uk",
    },
    {
      no: "55",
      name: "Urdu",
      native: "اردو",
      code: "ur",
    },
    {
      no: "56",
      name: "Vietnamese",
      native: "Tiếng Việt",
      code: "vi",
    },
    {
      no: "57",
      name: "Welsh",
      native: "Cymraeg",
      code: "cy",
    },
    {
      no: "58",
      name: "Yiddish",
      native: "ייִדיש",
      code: "yi",
    },{
        no: "59",
        name: "Latvian",
        native: "Latviešu",
        code: "lv",
      },
      {
        no: "60",
        name: "Lithuanian",
        native: "Lietuvių kalba",
        code: "lt",
      },
      {
        no: "61",
        name: "Macedonian",
        native: "Македонски",
        code: "mk",
      },
      {
        no: "58",
        name: "Malay",
        native: "Malay",
        code: "ms",
      },
      {
        no: "59",
        name: "Maltese",
        native: "Malti",
        code: "mt",
      },
      {
        no: "60",
        name: "Norwegian",
        native: "Norsk",
        code: "no",
      },
      {
        no: "61",
        name: "Persian",
        native: "فارسی",
        code: "fa",
      },
      {
        no: "62",
        name: "Polish",
        native: "Polski",
        code: "pl",
      },

  ];